site_name: Campus Game-Wit's Quest
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - search.suggest

nav:
  - Home: index.md
  - Dev Plan: dev-plan.md
  - System Design: system-design.md
  - UI Design:
    - Authentication UI: authentication-ui.md
  - Decisions: decisions.md
  - Meeting Minutes:
    - Meeting-minutes-1: meeting-minutes-1.md
    - Meeting-minutes-2: meeting-minutes-2.md
    - Meeting-minutes-3: meeting-minutes-3.md
  - Acceptance Criteria: 
    - Sprint-1:
      - Acceptance Criteria 1: sprint-1(UAT).md
      - Acceptance Criteria 2: sprint-1(US).md

    
