site_name: "Campus Game-Wit's Quest"
theme:
  name: readthedocs

plugins:
  - search
  - mermaid2

extra_css:
  - stylesheets/extra.css



nav:
  - Home: index.md
  - Planning:
    - Project Plan: Planning/project-plan.md
    - Sprint Plan: Planning/sprint-plan.md
    - Dev Plan: Planning/dev-plan.md
    - Decisions: Planning/decisions.md
  - Design:
    - System Design: Design/system-design.md
    - UI Design:
      - Authentication UI: Design/UI Design/authentication-ui.md
  - Sprints:
    - Sprint 1:
      - Sprint 1 Burndown Chart: Sprints/Sprint 1/sprint-1-burndown-chart.md
      - Acceptance Criteria 1: Sprints/Sprint 1/sprint-1(UAT).md
      - Sprint 1 Backlog: Sprints/Sprint 1/sprint-1-backlog.md
      - Sprint 1 Retrospective: Sprints/Sprint 1/sprint-1-retrospective.md
    - Sprint 2:
      - Sprint 2 Burndown Chart: Sprints/sprint-2-burndown-chart.md
      - Acceptance Criteria 1:  Sprints/sprint-2(UAT).md
      - Acceptance Criteria 2: Sprints/sprint-2(US).md
      - Sprint 2 Retrospective: Sprints/sprint-2-retrospective.md
    - Sprint 3:
      - Sprint 3 Burndown Chart: sprint-3-burndown-chart.md
      - Acceptance Criteria 1: sprint-3(UAT).md
      - Acceptance Criteria 2: sprint-3(US).md
      - Sprint 3 Retrospective: sprint-3-retrospective.md
  - Meeting Minutes:
    - Sprint 1:
      - Meeting 1: Meeting Minutes/Sprint 1/meeting-minutes-1.md
      - Meeting 2: Meeting Minutes/Sprint 1/meeting-minutes-2.md
      - Meeting 3: Meeting Minutes/Sprint 1/meeting-minutes-3.md
